import { eq, sql, and, desc, inArray, isNull, gt } from "drizzle-orm";
import { compare, hash } from "bcryptjs";
import { createHash, randomBytes, randomInt, randomUUID } from "node:crypto";
import { generateResetToken, hashResetToken, verifyResetToken } from "./resetTokens";
import { createTotpUri, generateTotpSecret, verifyTotpCode } from "./totp";
import { drizzle } from "drizzle-orm/mysql2";
import { activityLogs, alerts, authCredentials, centerStaff, evidenceFiles, evacuationCenters, invitations, evacuees, InsertUser, resources, resourceTransactions, responderActions, reportExports, riskReports, systemSettings, users, weatherSnapshots } from "../drizzle/schema";
import { getResourceStatus, resolveNotificationDelivery } from "../shared/operations";
import { ENV } from "./_core/env";
import { storagePut } from "./storage";
import { broadcastAlert } from "./_core/realtime";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); } } return _db; }

export async function verifyDatabaseConnection(): Promise<boolean> {
  try {
    const db = await getDb();
    if (!db) return false;
    await db.execute(sql`SELECT 1`);
    return true;
  } catch (error) {
    console.warn("[Database] Connectivity check failed:", error);
    return false;
  }
}

export async function getUserByEmail(email: string) {
  const db = await getDb();
  if (!db) return undefined;
  const normalizedEmail = email.trim().toLowerCase();
  const rows = await db.select().from(users).where(eq(users.email, normalizedEmail)).limit(1);
  return rows[0];
}
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const role = user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "citizen"); const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, loginMethod: user.loginMethod, role, lastSignedIn: user.lastSignedIn ?? new Date() }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, role: values.role, lastSignedIn: values.lastSignedIn } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return rows[0]; }
export async function getUserById(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.id, id)).limit(1); return rows[0]; }
export async function listUsers() { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, name: users.name, email: users.email, role: users.role, accountStatus: users.accountStatus, loginMethod: users.loginMethod, isDemo: users.isDemo, demoExpiresAt: users.demoExpiresAt, twoFactorEnabled: users.twoFactorEnabled, lastSignedIn: users.lastSignedIn, createdAt: users.createdAt }).from(users).orderBy(desc(users.lastSignedIn)); }

export async function listResponders() { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, name: users.name, email: users.email, accountStatus: users.accountStatus, isDemo: users.isDemo }).from(users).where(eq(users.role, "responder")).orderBy(users.name); }
export async function provisionDemoAccount(input: { name: string; role: "admin" | "staff" | "responder" | "citizen"; expiresInDays: number }, provisionedBy: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const suffix = randomUUID().slice(0, 8); const email = `demo.${input.role}.${suffix}@likas.training`; const password = `Likas-${randomBytes(9).toString("base64url")}-2026`; const expiresAt = new Date(Date.now() + input.expiresInDays * 24 * 60 * 60 * 1000); const [created] = await db.insert(users).values({ openId: `demo:${randomUUID()}`, name: input.name.trim(), email, role: input.role, loginMethod: "demo", isDemo: true, demoExpiresAt: expiresAt, demoRevokedAt: null, demoRevokedBy: null, twoFactorEnabled: false }).$returningId(); await db.insert(authCredentials).values({ userId: created.id, email, passwordHash: await hash(password, 12) }); return { userId: created.id, email, password, role: input.role, expiresAt, provisionedBy }; }
export async function provisionDemoAccounts(expiresInDays: number, provisionedBy: number) { const roles = ["admin", "staff", "responder", "citizen"] as const; return Promise.all(roles.map((role) => provisionDemoAccount({ name: `${role[0].toUpperCase()}${role.slice(1)} training`, role, expiresInDays }, provisionedBy))); }
export async function listDemoAccounts() { const db = await getDb(); if (!db) return []; const rows = await db.select({ id: users.id, name: users.name, email: users.email, role: users.role, demoExpiresAt: users.demoExpiresAt, demoRevokedAt: users.demoRevokedAt, demoRevokedBy: users.demoRevokedBy, createdAt: users.createdAt, lastSignedIn: users.lastSignedIn }).from(users).where(eq(users.isDemo, true)).orderBy(desc(users.createdAt)); const now = Date.now(); return rows.map((row) => ({ ...row, status: row.demoRevokedAt ? "REVOKED" as const : row.demoExpiresAt && row.demoExpiresAt.getTime() <= now ? "EXPIRED" as const : "ACTIVE" as const })); }
export async function revokeDemoAccount(userId: number, revokedBy: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select({ id: users.id, isDemo: users.isDemo, demoRevokedAt: users.demoRevokedAt }).from(users).where(eq(users.id, userId)).limit(1); const user = rows[0]; if (!user?.isDemo) throw new Error("Demo account not found"); if (user.demoRevokedAt) return { userId, revoked: true, alreadyRevoked: true as const }; const revokedAt = new Date(); await db.update(users).set({ demoRevokedAt: revokedAt, demoRevokedBy: revokedBy, demoExpiresAt: revokedAt, twoFactorSecret: null, twoFactorEnabled: false }).where(eq(users.id, userId)); return { userId, revoked: true, alreadyRevoked: false as const }; }
export async function getTwoFactorStatus(userId: number) { const user = await getUserById(userId); if (!user) throw new Error("User not found"); return { eligible: user.role === "responder", enabled: Boolean(user.twoFactorEnabled), setupPending: Boolean(user.twoFactorSecret && !user.twoFactorEnabled), role: user.role }; }
export async function beginTwoFactorSetup(userId: number) { const user = await getUserById(userId); if (!user || user.role !== "responder") throw new Error("Two-factor authentication is only available to responders"); if (user.twoFactorEnabled) throw new Error("Disable existing two-factor authentication before creating a new setup"); const secret = generateTotpSecret(); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ twoFactorSecret: secret, twoFactorEnabled: false }).where(eq(users.id, userId)); return { secret, otpauthUrl: createTotpUri(secret, user.email || `user-${userId}`) }; }
export async function confirmTwoFactorSetup(userId: number, code: string) { const user = await getUserById(userId); if (!user || !user.twoFactorSecret || user.role !== "responder") throw new Error("Start two-factor setup before confirming it"); if (!verifyTotpCode(user.twoFactorSecret, code)) throw new Error("The verification code is not valid or has expired"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ twoFactorEnabled: true }).where(eq(users.id, userId)); return { enabled: true }; }
export async function disableTwoFactor(userId: number) { const user = await getUserById(userId); if (!user || user.role !== "responder") throw new Error("Two-factor authentication is only available to responders"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ twoFactorSecret: null, twoFactorEnabled: false }).where(eq(users.id, userId)); return { enabled: false }; }
export async function verifyUserTotp(userId: number, code: string) { const user = await getUserById(userId); return Boolean(user && user.twoFactorEnabled && user.role === "responder" && verifyTotpCode(user.twoFactorSecret, code)); }
export async function updateUserRole(userId: number, role: "admin" | "staff" | "responder" | "citizen" | "user") { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ role }).where(eq(users.id, userId)); return { userId, role }; }
export async function updateUserApproval(userId: number, accountStatus: "APPROVED" | "REJECTED") { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const target = await getUserById(userId); if (!target || target.role !== "citizen") throw new Error("Only citizen registrations can be approved or declined"); await db.update(users).set({ accountStatus }).where(eq(users.id, userId)); return { userId, accountStatus }; }
export async function listActivityLogs(entityType?: string) { const db = await getDb(); if (!db) return []; return db.select().from(activityLogs).where(entityType ? eq(activityLogs.entityType, entityType) : undefined).orderBy(desc(activityLogs.createdAt)).limit(100); }
export async function listCenters() { const db = await getDb(); if (!db) return []; return db.select().from(evacuationCenters).orderBy(desc(evacuationCenters.updatedAt)); }
export async function listCentersForUser(userId: number) { const db = await getDb(); if (!db) return []; return db.select({ center: evacuationCenters }).from(evacuationCenters).innerJoin(centerStaff, eq(centerStaff.centerId, evacuationCenters.id)).where(eq(centerStaff.userId, userId)).orderBy(desc(evacuationCenters.updatedAt)).then(rows => rows.map(row => row.center)); }
export async function listAssignedCenterIds(userId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select({ centerId: centerStaff.centerId }).from(centerStaff).where(eq(centerStaff.userId, userId)); return rows.map(row => row.centerId); }
export async function upsertCenter(input: typeof evacuationCenters.$inferInsert, id?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = id ? (await db.select({ maximumCapacity: evacuationCenters.maximumCapacity, currentOccupancy: evacuationCenters.currentOccupancy }).from(evacuationCenters).where(eq(evacuationCenters.id, id)).limit(1))[0] : undefined; const maximumCapacity = input.maximumCapacity ?? existing?.maximumCapacity; const currentOccupancy = input.currentOccupancy ?? existing?.currentOccupancy ?? 0; if (!maximumCapacity || maximumCapacity < 1) throw new Error("Capacity must be greater than zero"); if (currentOccupancy < 0 || currentOccupancy > maximumCapacity) throw new Error("Occupancy must be between zero and capacity"); if (id) { await db.update(evacuationCenters).set(input).where(eq(evacuationCenters.id, id)); return { id }; } const [created] = await db.insert(evacuationCenters).values(input).$returningId(); return created; }
export async function archiveCenter(centerId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(evacuationCenters).set({ status: "CLOSED" }).where(eq(evacuationCenters.id, centerId)); return { centerId, archived: true }; }
export async function assignCenterStaff(centerId: number, userId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(centerStaff).values({ centerId, userId }).$returningId(); return created; }
export async function getOperationsSummary() { const db = await getDb(); if (!db) return { centers: 0, evacuees: 0, capacity: 0, resources: 0, activeAlerts: 0, pendingReports: 0 }; const [centerRows, evacueeRows, resourceRows, alertRows, reportRows] = await Promise.all([db.select({ count: sql<number>`count(*)`, capacity: sql<number>`coalesce(sum(${evacuationCenters.maximumCapacity}),0)`, occupancy: sql<number>`coalesce(sum(${evacuationCenters.currentOccupancy}),0)` }).from(evacuationCenters), db.select({ count: sql<number>`count(*)` }).from(evacuees).where(eq(evacuees.status, "ACTIVE")), db.select({ quantity: sql<number>`coalesce(sum(${resources.quantity}),0)` }).from(resources), db.select({ count: sql<number>`count(*)` }).from(alerts).where(eq(alerts.isActive, true)), db.select({ count: sql<number>`count(*)` }).from(riskReports).where(and(eq(riskReports.status, "PENDING"), eq(riskReports.priority, "CRITICAL")))]); const c = centerRows[0] ?? { count: 0, capacity: 0, occupancy: 0 }; return { centers: Number(c.count), evacuees: Number(evacueeRows[0]?.count ?? 0), capacity: Number(c.capacity), occupancy: Number(c.occupancy), availableSlots: Math.max(0, Number(c.capacity) - Number(c.occupancy)), resources: Number(resourceRows[0]?.quantity ?? 0), activeAlerts: Number(alertRows[0]?.count ?? 0), pendingReports: Number(reportRows[0]?.count ?? 0) }; }
export async function registerEvacuee(input: typeof evacuees.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.transaction(async (tx) => { const centers = await tx.select().from(evacuationCenters).where(eq(evacuationCenters.id, input.centerId)).limit(1); const center = centers[0]; if (!center) throw new Error("Evacuation center not found"); if (center.status !== "OPEN" || center.currentOccupancy >= center.maximumCapacity) throw new Error("This center cannot accept another evacuee"); const [created] = await tx.insert(evacuees).values(input).$returningId(); await tx.update(evacuationCenters).set({ currentOccupancy: sql`${evacuationCenters.currentOccupancy} + 1`, status: sql`case when ${evacuationCenters.currentOccupancy} + 1 >= ${evacuationCenters.maximumCapacity} then 'FULL' else ${evacuationCenters.status} end` }).where(eq(evacuationCenters.id, input.centerId)); return created; }); }
export async function transferEvacuee(evacueeId: number, targetCenterId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.transaction(async (tx) => { const rows = await tx.select().from(evacuees).where(eq(evacuees.id, evacueeId)).limit(1); const person = rows[0]; if (!person || person.status !== "ACTIVE") throw new Error("Active evacuee not found"); const targetRows = await tx.select().from(evacuationCenters).where(eq(evacuationCenters.id, targetCenterId)).limit(1); const target = targetRows[0]; if (!target || target.status !== "OPEN" || target.currentOccupancy >= target.maximumCapacity) throw new Error("Target center cannot accept this transfer"); await tx.update(evacuees).set({ centerId: targetCenterId, status: "TRANSFERRED" }).where(eq(evacuees.id, evacueeId)); await tx.update(evacuationCenters).set({ currentOccupancy: sql`${evacuationCenters.currentOccupancy} - 1` }).where(eq(evacuationCenters.id, person.centerId)); await tx.update(evacuationCenters).set({ currentOccupancy: sql`${evacuationCenters.currentOccupancy} + 1` }).where(eq(evacuationCenters.id, targetCenterId)); return { evacueeId, targetCenterId }; }); }
export async function releaseEvacuee(evacueeId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.transaction(async (tx) => { const rows = await tx.select().from(evacuees).where(eq(evacuees.id, evacueeId)).limit(1); const person = rows[0]; if (!person || person.status !== "ACTIVE") throw new Error("Active evacuee not found"); await tx.update(evacuees).set({ status: "RELEASED" }).where(eq(evacuees.id, evacueeId)); await tx.update(evacuationCenters).set({ currentOccupancy: sql`greatest(${evacuationCenters.currentOccupancy} - 1, 0)`, status: sql`case when ${evacuationCenters.status} = 'FULL' then 'OPEN' else ${evacuationCenters.status} end` }).where(eq(evacuationCenters.id, person.centerId)); return { evacueeId }; }); }
export async function listEvacuees(centerId?: number) { const db = await getDb(); if (!db) return []; return db.select().from(evacuees).where(centerId ? eq(evacuees.centerId, centerId) : undefined).orderBy(desc(evacuees.registrationDate)); }
export async function getEvacueeById(evacueeId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(evacuees).where(eq(evacuees.id, evacueeId)).limit(1); return rows[0]; }
export async function listEvacueesForCenters(centerIds: number[]) { if (!centerIds.length) return []; const db = await getDb(); if (!db) return []; return db.select().from(evacuees).where(inArray(evacuees.centerId, centerIds)).orderBy(desc(evacuees.registrationDate)); }
export async function listResources(centerId?: number) { const db = await getDb(); if (!db) return []; return db.select().from(resources).where(centerId ? eq(resources.centerId, centerId) : undefined).orderBy(desc(resources.updatedAt)); }
export async function getResourceById(resourceId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(resources).where(eq(resources.id, resourceId)).limit(1); return rows[0]; }
export async function listResourcesForCenters(centerIds: number[]) { if (!centerIds.length) return []; const db = await getDb(); if (!db) return []; return db.select().from(resources).where(inArray(resources.centerId, centerIds)).orderBy(desc(resources.updatedAt)); }
export async function createResource(input: typeof resources.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(resources).values(input).$returningId(); return created; }
export async function updateResource(resourceId: number, input: Partial<typeof resources.$inferInsert>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(resources).set(input).where(eq(resources.id, resourceId)); return { id: resourceId }; }
export async function removeResource(resourceId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(resources).set({ quantity: 0, status: "OUT_OF_STOCK" }).where(eq(resources.id, resourceId)); return { id: resourceId, removed: true }; }
export async function transactResource(resourceId: number, userId: number, type: "STOCK_IN" | "STOCK_OUT" | "TRANSFER" | "BORROW" | "RETURN", quantity: number, notes?: string) { const db = await getDb(); if (!db || quantity <= 0) throw new Error("Invalid resource transaction"); return db.transaction(async (tx) => { const rows = await tx.select().from(resources).where(eq(resources.id, resourceId)).limit(1); const resource = rows[0]; if (!resource) throw new Error("Resource not found"); const delta = type === "STOCK_OUT" || type === "BORROW" ? -quantity : quantity; if (resource.quantity + delta < 0) throw new Error("Insufficient stock"); const nextQuantity = resource.quantity + delta; const nextStatus = getResourceStatus(nextQuantity, resource.minimumStock, resource.expirationDate); await tx.update(resources).set({ quantity: nextQuantity, status: nextStatus }).where(eq(resources.id, resourceId)); const [created] = await tx.insert(resourceTransactions).values({ resourceId, userId, type, quantity, notes }).$returningId(); return created; }); }
export async function listResourceTransactions(resourceId?: number) { const db = await getDb(); if (!db) return []; return db.select().from(resourceTransactions).where(resourceId ? eq(resourceTransactions.resourceId, resourceId) : undefined).orderBy(desc(resourceTransactions.createdAt)); }
export async function createRiskReport(input: typeof riskReports.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(riskReports).values(input).$returningId(); return created; }
export async function listRiskReports() { const db = await getDb(); if (!db) return []; return db.select().from(riskReports).orderBy(desc(riskReports.createdAt)); }
export async function listRiskReportsForUser(userId: number, role: string) { const db = await getDb(); if (!db) return []; if (role === "citizen" || role === "user") return db.select().from(riskReports).where(eq(riskReports.reporterId, userId)).orderBy(desc(riskReports.createdAt)); if (role === "responder" || role === "admin" || role === "staff") return listRiskReports(); return []; }
export async function getRiskReportById(reportId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(riskReports).where(eq(riskReports.id, reportId)).limit(1); return rows[0]; }
export async function isResponderAssignedToReport(reportId: number, userId: number) { const report = await getRiskReportById(reportId); return report?.assignedResponderId === userId; }
export async function updateRiskReport(reportId: number, input: Partial<typeof riskReports.$inferInsert>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(riskReports).set(input).where(eq(riskReports.id, reportId)); return { reportId }; }
export async function createResponderAction(input: typeof responderActions.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(responderActions).values(input).$returningId(); return created; }
export async function listResponderActions(reportId: number) { const db = await getDb(); if (!db) return []; return db.select().from(responderActions).where(eq(responderActions.reportId, reportId)).orderBy(responderActions.createdAt); }
export async function listAlerts() { const db = await getDb(); if (!db) return []; return db.select().from(alerts).where(eq(alerts.isActive, true)).orderBy(desc(alerts.createdAt)); }
export async function logActivity(input: typeof activityLogs.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(activityLogs).values(input); }
export async function createAlert(input: typeof alerts.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(alerts).values(input).$returningId(); const delivery = resolveNotificationDelivery({ emailConfigured: Boolean(process.env.EMAIL_PROVIDER_KEY), smsConfigured: Boolean(process.env.SMS_PROVIDER_KEY) }); return { ...created, delivery }; }
export async function uploadEvidence(input: { reportId: number; userId: number; fileName: string; mimeType: string; dataBase64: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (!input.mimeType.startsWith("image/") && input.mimeType !== "application/pdf") throw new Error("Only images and PDF evidence are supported"); const cleanName = input.fileName.replace(/[^a-zA-Z0-9._-]/g, "_"); const bytes = Buffer.from(input.dataBase64.replace(/^data:[^;]+;base64,/, ""), "base64"); if (bytes.byteLength > 10_000_000) throw new Error("Evidence file exceeds 10MB"); const stored = await storagePut(`risk-reports/${input.reportId}/${input.userId}-${cleanName}`, bytes, input.mimeType); const [created] = await db.insert(evidenceFiles).values({ reportId: input.reportId, fileKey: stored.key, fileUrl: stored.url, fileName: cleanName, mimeType: input.mimeType, sizeBytes: bytes.byteLength }).$returningId(); return { ...created, url: stored.url }; }
export async function getWeatherSnapshot() { const db = await getDb(); const apiKey = process.env.WEATHER_API_KEY; if (apiKey) { try { const response = await fetch(`https://api.openweathermap.org/data/2.5/weather?lat=14.544&lon=121.071&units=metric&appid=${apiKey}`); if (response.ok) { const payload = await response.json() as { main?: { temp?: number }; weather?: Array<{ description?: string }>; }; const result = { location: "Pateros", temperature: payload.main?.temp ?? null, condition: payload.weather?.[0]?.description ?? "Unknown", warning: null, provider: "OpenWeather" }; if (db) await db.insert(weatherSnapshots).values({ location: result.location, temperatureC: result.temperature?.toString(), condition: result.condition, provider: result.provider }); return result; } } catch { /* Provider failure intentionally falls through to in-app fallback. */ } } const fallback = { location: "Pateros", temperature: 29, condition: "Partly cloudy", warning: "Rain watch · provider not configured", provider: "In-app fallback" }; if (db) await db.insert(weatherSnapshots).values({ location: fallback.location, temperatureC: fallback.temperature.toString(), condition: fallback.condition, warning: fallback.warning, provider: fallback.provider }); return fallback; }
export async function updateSetting(settingKey: string, settingValue: string, updatedBy: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(systemSettings).values({ settingKey, settingValue, updatedBy }).onDuplicateKeyUpdate({ set: { settingValue, updatedBy } }); return { settingKey, settingValue }; }
export async function getSettings(keys: string[]) { const db = await getDb(); if (!db) return []; if (!keys.length) return []; return db.select().from(systemSettings).where(inArray(systemSettings.settingKey, keys)); }
export async function getPublicSmsSettings() { const rows = await getSettings(["sms_official_number", "sms_provider"]); return { officialNumber: rows.find((row) => row.settingKey === "sms_official_number")?.settingValue || "09171234567", provider: rows.find((row) => row.settingKey === "sms_provider")?.settingValue || "NONE" }; }
export async function createInvitation(input: { email: string; name: string; role: "staff" | "responder" }, invitedBy: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const token = randomUUID(); const tokenHash = createHash("sha256").update(token).digest("hex"); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); const [created] = await db.insert(invitations).values({ email: input.email.trim().toLowerCase(), name: input.name.trim(), role: input.role, tokenHash, invitedBy, expiresAt }).$returningId(); return { ...created, email: input.email.trim().toLowerCase(), name: input.name.trim(), role: input.role, expiresAt, inviteToken: token }; }
export async function listInvitations() { const db = await getDb(); if (!db) return []; return db.select().from(invitations).orderBy(desc(invitations.createdAt)).limit(100); }
export async function acceptInvitation(token: string, password: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const tokenHash = createHash("sha256").update(token).digest("hex"); return db.transaction(async (tx) => { const rows = await tx.select().from(invitations).where(and(eq(invitations.tokenHash, tokenHash), isNull(invitations.acceptedAt), gt(invitations.expiresAt, new Date()))).limit(1); const invitation = rows[0]; if (!invitation) throw new Error("Invitation is invalid or expired"); const existing = await tx.select().from(users).where(eq(users.email, invitation.email)).limit(1); let user = existing[0]; if (!user) { const [created] = await tx.insert(users).values({ openId: `local:${randomUUID()}`, email: invitation.email, name: invitation.name, role: invitation.role, loginMethod: "invitation" }).$returningId(); const createdRows = await tx.select().from(users).where(eq(users.id, created.id)).limit(1); user = createdRows[0]; } else { await tx.update(users).set({ name: invitation.name, role: invitation.role }).where(eq(users.id, user.id)); }
      if (!user) throw new Error("Unable to create invited user");
      await tx.insert(authCredentials).values({ userId: user.id, email: invitation.email, passwordHash: await hash(password, 12) }).onDuplicateKeyUpdate({ set: { passwordHash: await hash(password, 12) } });
      await tx.update(invitations).set({ acceptedAt: new Date() }).where(eq(invitations.id, invitation.id));
      await tx.insert(activityLogs).values({ actorId: invitation.invitedBy, action: "INVITATION_ACCEPTED", entityType: "user", entityId: user.id, metadata: JSON.stringify({ invitationId: invitation.id, email: invitation.email, role: invitation.role }) });
      return { userId: user.id, email: invitation.email, role: invitation.role };
    }); }
export async function queueReportExport(requestedBy: number, reportType: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [created] = await db.insert(reportExports).values({ requestedBy, reportType, status: "QUEUED" }).$returningId(); return created; }
export async function registerLocalUser(input: { email: string; password: string; name: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const normalizedEmail = input.email.trim().toLowerCase(); const existing = await db.select().from(authCredentials).where(eq(authCredentials.email, normalizedEmail)).limit(1); if (existing[0]) throw new Error("An account with this email already exists"); const duplicateUser = await db.select().from(users).where(eq(users.email, normalizedEmail)).limit(1); if (duplicateUser[0]) throw new Error("An account with this email already exists"); const openId = `local:${randomUUID()}`; const [createdUser] = await db.insert(users).values({ openId, email: normalizedEmail, name: input.name.trim(), role: "citizen", loginMethod: "password", accountStatus: "PENDING" }).$returningId(); await db.insert(authCredentials).values({ userId: createdUser.id, email: normalizedEmail, passwordHash: await hash(input.password, 12) }); return { userId: createdUser.id, openId, email: normalizedEmail, name: input.name.trim(), role: "citizen" as const }; }
export async function verifyLocalEmail(email: string, token: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const normalizedEmail = email.trim().toLowerCase(); const rows = await db.select({ credential: authCredentials, user: users }).from(authCredentials).innerJoin(users, eq(users.id, authCredentials.userId)).where(eq(authCredentials.email, normalizedEmail)).limit(1); const record = rows[0]; if (!record || record.user.emailVerifiedAt || !record.credential.emailVerificationTokenHash || !record.credential.emailVerificationExpiresAt || record.credential.emailVerificationExpiresAt.getTime() <= Date.now() || !(await compare(token, record.credential.emailVerificationTokenHash))) throw new Error("The verification code is invalid or expired"); await db.update(users).set({ emailVerifiedAt: new Date() }).where(eq(users.id, record.user.id)); await db.update(authCredentials).set({ emailVerificationTokenHash: null, emailVerificationExpiresAt: null }).where(eq(authCredentials.id, record.credential.id)); return record.user; }
export async function verifyLocalCredentials(email: string, password: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const normalizedEmail = email.trim().toLowerCase(); const credentials = await db.select().from(authCredentials).where(eq(authCredentials.email, normalizedEmail)).limit(1); const credential = credentials[0]; if (!credential || !(await compare(password, credential.passwordHash))) return null; const rows = await db.select().from(users).where(eq(users.id, credential.userId)).limit(1); const user = rows[0]; if (!user) return null; if (user.isDemo && (user.demoRevokedAt || (user.demoExpiresAt && user.demoExpiresAt.getTime() <= Date.now()))) return null; return user; }
export async function issuePasswordReset(email: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const normalizedEmail = email.trim().toLowerCase(); const token = generateResetToken(); const existing = await db.select().from(authCredentials).where(eq(authCredentials.email, normalizedEmail)).limit(1); if (!existing[0]) throw new Error("No account found with this email address."); await db.update(authCredentials).set({ resetTokenHash: hashResetToken(token), resetExpiresAt: new Date(Date.now() + 30 * 60 * 1000) }).where(eq(authCredentials.email, normalizedEmail)); return token; }
export async function resetLocalPassword(email: string, token: string, newPassword: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const normalizedEmail = email.trim().toLowerCase(); const rows = await db.select().from(authCredentials).where(eq(authCredentials.email, normalizedEmail)).limit(1); const credential = rows[0]; if (!credential) throw new Error("No recovery request found for this email. Request a token first."); if (!credential.resetTokenHash || !credential.resetExpiresAt || credential.resetExpiresAt.getTime() < Date.now()) throw new Error("Reset token has expired. Please request a new recovery token."); if (!credential.resetTokenHash || !verifyResetToken(token, credential.resetTokenHash)) throw new Error("Reset token is invalid. Please check the token and try again."); await db.update(authCredentials).set({ passwordHash: await hash(newPassword, 12), resetTokenHash: null, resetExpiresAt: null }).where(eq(authCredentials.id, credential.id)); return { success: true }; }
export async function changeLocalPassword(userId: number, currentPassword: string, newPassword: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select().from(authCredentials).where(eq(authCredentials.userId, userId)).limit(1); const credential = rows[0]; if (!credential || !(await compare(currentPassword, credential.passwordHash))) throw new Error("Current password is incorrect"); await db.update(authCredentials).set({ passwordHash: await hash(newPassword, 12) }).where(eq(authCredentials.userId, userId)); return { success: true }; }
